version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build: .
    depends_on:
      - mongo
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://mongo:27017
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  test:
    build: .
    depends_on:
      - api
    volumes:
      - ./tests:/tests
    environment:
      - API_URL=http://api:8000
    command: >
      sh -c "pip install pytest pytest-xdist && pytest -n auto /tests"

volumes:
  mongo_data:
