name: Run API Tests

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        options: --health-cmd="curl --silent --fail localhost:27017 || exit 1" --health-interval=30s --health-timeout=30s --health-retries=3
        ports:
          - 27017:27017

    steps:
    # Check out the repository
    - name: Check out the repository
      uses: actions/checkout@v2

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest requests-mock

    # Run tests
    - name: Run tests
      run: |
        pytest --maxfail=1 --disable-warnings -q
      continue-on-error: true

    # Upload test reports as artifacts
    - name: Upload test reports as artifacts
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: ./tests/test_reports/

    # Archive and store pytest test results (optional)
    - name: Archive Test Results
      if: always()
      run: |
        mkdir -p ./tests/test_reports/
        mv pytest-report.xml ./tests/test_reports/
