name: Run API Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:latest
        options: --health-cmd='exit 0' --health-interval=10s --health-timeout=5s --health-retries=3 --network host
        ports:
          - 27017:27017
    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # Install Docker Compose
      - name: Set up Docker Compose
        run: |
          sudo apt-get install docker-compose

      # Build and run the Dockerized environment
      - name: Run Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d

      # Run tests in parallel
      - name: Run tests
        run: |
          pytest tests --maxfail=1 --disable-warnings --maxfail=1 --tb=short -n auto

      # Upload test results
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: tests/test_reports/

      # Shut down the Docker containers
      - name: Shutdown Docker
        run: |
          docker-compose down
