name: CI Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  IMAGE_ID: oms-${{ github.run_id }}

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker Image with Repository
      run: |
        # Build the Docker image using the Dockerfile in the repo
        docker build -t ${{ env.IMAGE_ID }} .

    - name: Run tests in Docker Container
      run: |
        # Run pytest in the container
        docker run --rm -v $GITHUB_WORKSPACE:/workspace -w /workspace ${{ env.IMAGE_ID }} \
          sh -c "pip install -r requirements.txt && PYTHONPATH=tests pytest tests -v" > result.log || true

    - name: Upload Test Results as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: pytest-results
        path: result.log