name: CI Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  IMAGE_ID: oms-${{ github.run_id }}

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build & Run Docker Compose
      run: |
        docker-compose -p ${{ env.IMAGE_ID }} up --build --abort-on-container-exit

    - name: Commit API Container to Image
      run: |
        docker ps -a
        API_CONTAINER=$(docker ps -aqf "name=${{ env.IMAGE_ID }}_api")
        docker commit $API_CONTAINER ${{ env.IMAGE_ID }}-api:latest
        docker save ${{ env.IMAGE_ID }}-api:latest -o api-image.tar

    - name: Commit Test Container to Image
      run: |
        TEST_CONTAINER=$(docker ps -aqf "name=${{ env.IMAGE_ID }}_test")
        docker commit $TEST_CONTAINER ${{ env.IMAGE_ID }}-test:latest
        docker save ${{ env.IMAGE_ID }}-test:latest -o test-image.tar

    - name: Upload API Image Artifact
      uses: actions/upload-artifact@v3
      with:
        name: api-image-${{ env.IMAGE_ID }}
        path: api-image.tar

    - name: Upload Test Image Artifact
      uses: actions/upload-artifact@v3
      with:
        name: test-image-${{ env.IMAGE_ID }}
        path: test-image.tar
